#!/bin/bash
if (($# == 3 )); then
    ssh "$2" "own $1 \"$3\""
else
echo "Connected to $(hostname).";
spacebuffer=$(i=0; while ((i < 2000)); do echo " "; i=$((i+1)); done);

for var in $( ps -e --User "$1" | grep ' pts/' | cut -c7-14 | uniq );
do
    echo "Message sent to $var...";
    cat <(echo "$spacebuffer") <(echo -e "$2" | figlet -c) | write "$1" "$var"
done

echo "Task complete.";

exit

fi
~  
