#!/bin/sh
# Shell script to start Vim with less.vim.
# Read stdin if no arguments were given.

files=$@
if [ -z "$files" ]; then files="-"; fi

less_vim() {
	vim -R -c 'set ts=8' -c 'let no_plugin_maps = 1' -c 'runtime! macros/less.vim' -c 'set mouse=h' "$@"
}

do_ps() {
	ps fauxw
}

pproc() {
	if uname -s | grep -iq linux; then
		ps -p $1 -o comm=
	elif uname -s | grep -iq cygwin; then
		ps -p $1 | sed -e 's/^I/ /' | grep -v PID
	fi
}

ppid() {
	if uname -s | grep -iq linux; then
		ps -p $1 -o ppid=
	elif uname -s | grep -iq cygwin; then
		ps -p $1 | sed -e 's/^I/ /' | grep -v PID | awk '{print $2}'
	fi
}

# Check if called from man or perldoc
if do_ps | grep -q '\(man\|perl\(doc\|$\)\)\>'; then
	proc=$$
	while next_parent=`ppid $proc` && [ $next_parent != 1 ]; do
		if pproc $next_parent | grep -q 'man\>'; then
			perl -pi -e 's/\e\[[^m]*m//g' | col -b | less_vim -c 'set ft=man' -; exit
		elif pproc $next_parent | grep -q 'perl\(doc\|$\)\>'; then
			col -b < $files | less_vim -c "set ft=man" -; exit
		fi
		proc=$next_parent
	done
fi

less_vim $files
